---
- hosts: webservers

  tasks:
  - name: Add lines to a Dockerfile
    lineinfile:
      path: /home/devasc/project_site/Dockerfile
      line: |
        FROM httpd:alpine
        COPY ./index.html /usr/local/apache2/htdocs/
        EXPOSE 80
        CMD ["httpd-foreground"]

  - name: Build a docker image.
    command: docker build -t website /home/devasc/project_site/

  - name: Run a docker container.
    command: docker run -t -d -p 8080:80 --name web_container website
